url: https://mainstreettitledeveloper.github.io

# Site settings
title: Main Street Title LLC
email: mainstreettitledeveloper@gmail.com
description: "Main Street Title is a Shreveport - Bossier City title company providing the best real estate closing and title services for all of Northwest Louisiana."


# Team names, titles and social links
people:
- name: Charles
  pic: charles
  position: Lead Engineer
 
- name: Amy
  pic: amy
  position: Lead Marketer

- name: Adrienne
  pic: adrienne
  position: Lead Developer
      
- name: Carla
  pic: carla
  position: Lead Engineer
 
- name: Morgan
  pic: morgan
  position: Lead Marketer

- name: Gaelan
  pic: gaelan
  position: Lead Developer
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
