url: https://mainstreettitledeveloper.github.io

# Site settings
title: Main Street Title LLC
email: auv-iiitdm@gmail.com
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Charles
  pic: charles
  position: Lead Engineer
 
- name: Amy
  pic: amy
  position: Lead Marketer

- name: Adrienne
  pic: adrienne
  position: Lead Developer
      
- name: Carla
  pic: carla
  position: Lead Developer
  
  - name: Morgan
  pic: morgan
  position: Lead Developer
  
  - name: Gaelan
  pic: gaelan
  position: Lead Developer
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: IIITDM Kancheepuram
  - line: Chennai-600127

# Build settings
markdown: kramdown
permalink: pretty
