url: https://mainstreettitledeveloper.github.io

# Site settings
title: Main Street Title LLC
email: mainstreettitledeveloper@gmail.com
description: "Main Street Title is a Shreveport - Bossier City title company providing the best real estate closing and title services for all of Northwest Louisiana."


# Team names, titles and social links
people:
- name: Charles J. Neupert Jr.
  pic: charles
  position: Attorney-at-Law
  social:
    - title: envelope
      email: test@gmail.com
      url: #CNeupert@neupertlaw.com
 
- name: Amy E. Hall
  pic: amy
  position: Manager
  social:
    - title: envelope
      url: mailto:CNeupert@neupertlaw.com

- name: Adrienne S. Remedies
  pic: adrienne
  position: Escrow Officer
      
- name: Carla Dement
  pic: carla
  position: Post-Closing Supervisor
 
- name: Morgan Hope
  pic: morgan
  position: Courier/Receptionist

- name: Gaelan Harrington
  pic: gaelan
  position: Website Developer
 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:

# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Build settings
markdown: kramdown
permalink: pretty
